### ISSUE TITLE
Add `tap_action`

### ISSUE THREAD

**Issue by tomoqv** [DSorlov/hasl-lovelace#6]
I want to bring up e.g. a pop-up card with more details when tapping the `hasl-card`.

**Comment by dimmanramone** [comment]
I'll look into it but you should be able to do what you want with https://github.com/thomasloven/hass-browser_mod

**Comment by tomoqv** [comment]
That is what I thought and I actually tried to add the `service: browser_mod.popup`, but there must be a recognizable "tap" on the hasl-card, which seems not to be the case. Most cards seem to show at least a more-info when tapped, but when I tap the hasl-card it just places a cursor in that card.
Here is my code, but how do I get the actual "tap" recognized?
```
      - type: "custom:hasl-departure-card"
        header: false
        departures: true
        timeleft: false
        updated: false
        name: "Trafikinfo"
        hide_departed: true
        language: sv-SE
        entities:
          - sensor.mossens_ip
          - sensor.alleparken

```
